### PR TITLE
Documentation update for boot2docker users

### PR DESCRIPTION
**Pull request by msamblanet**
Boot2docker will only map volumes located under /Users (mac) or c:\Users (Windows) by default.  Added a note to the readme (both static and generated) with warnings about this.

Created similar PR for the connect project also (since most people would likely be referencing that README.md) - https://github.com/anvilresearch/connect/pull/232

### CODE REVIEW

**Comment by adalinesimonian** [comment]
boot2docker has been deprecated, and in the docs repository, we have started to refer people to Docker Toolbox, which, if I'm not mistaken, uses docker-machine.

I'm on my phone, so pardon my unhelpfully brief response, but is this behaviour the same with the new instructions? They should be in connect-docs.

@christiansmith, we need to link to connect-docs for documentation in the other repositories so that our docs don't become fragmented and unmanageable

**Comment by msamblanet** [comment]
@vsimonian  - Docker-toolbox just includes docker-machine which in turn still uses the boot2docker.iso and has all the same issues...I'm actually running via a docker-toolbox install and I see this issue.  Had to move my project folder to get Connect running correctly.

Perhaps the text should be edited to refer to docker-toolbox or docker-machine instead then?  Docker did not leave us a single clean phrase to use here :(

**Comment by adalinesimonian** [comment]
Ah, the internals are the same? No kidding. Had no idea.

I think we should link to connect-docs and make sure the instructions there reflect behaviour accurately.

**Comment by christiansmith** [comment]
@msamblanet – we thought this through a little further and the consensus is that this addition should actually go in the [Running in Docker Containers](https://github.com/anvilresearch/connect-docs/blob/master/getting-started.md#running-in-docker-containers) section of the Getting Started guide in the [anvilresearch/connect-docs](https://github.com/anvilresearch/connect-docs) repo.

We plan to replace the getting started content in these READMEs with links to that set of documentation. 

Would you mind submitting a PR with these instructions to the docs repository? 

Thanks for this contribution!

**Comment by msamblanet** [comment]
Moved - see https://github.com/anvilresearch/connect-docs/pull/34

**Comment by adalinesimonian** [comment]
Merged https://github.com/anvilresearch/connect-docs/pull/34

**Pull request closed without merging**
