### PR TITLE
Fix for #38 - Pin redis and nginx versions

### PR DESCRIPTION
**Pull request by msamblanet**
See #38 

Split version into 2 env variables to ensure backwards compatability

Also added `apk update` to ensure we were using current package lists

Verified by building images on my Windows box successfully.  New images should be published once merged.

### CODE REVIEW

**Comment by christiansmith** [comment]
@msamblanet – minor issue with this. The nginx Dockerfile is trying to install redis instead of nginx. Can you push a fix? I'll try it out again and merge right away.

https://github.com/anvilresearch/connect-cli/pull/40/files#diff-58605f512474fc878d18d314b53c1ebdR19

**Comment by msamblanet** [comment]
Stupid me - cut and paste error somewhere on the way - will take care of it shortly

**Comment by msamblanet** [comment]
And fudge - pasted in a change I did not mean to...grrrr...

**Comment by msamblanet** [comment]
OK - think that should do it...

**Comment by christiansmith** [comment]
Tested and it now works. Thanks!

**Pull request merged**
